# Generated by Django 6.1 on 2026-08-28 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='school_hous_is_acti_f685f1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_house_code_when_set')],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='school.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='school.classsection')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='school.teacherprofile')),
            ],
            options={
                'ordering': ['-academic_year', 'class_section'],
                'indexes': [models.Index(fields=['academic_year', 'teacher'], name='school_clas_academi_29adaa_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_section', 'academic_year'), name='unique_class_teacher_per_section_year'), models.UniqueConstraint(fields=('teacher', 'academic_year'), name='unique_class_teacher_per_teacher_year')],
            },
        ),
        migrations.CreateModel(
            name='HouseMasterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_master_assignments', to='school.academicyear')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_assignments', to='school.house')),
                ('staff', models.ForeignKey(limit_choices_to={'category': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='house_master_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'house'],
                'indexes': [models.Index(fields=['academic_year', 'house'], name='school_hous_academi_fc5edc_idx'), models.Index(fields=['academic_year', 'staff'], name='school_hous_academi_8b585a_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'house', 'academic_year'), name='unique_house_master_assignment')],
            },
        ),
        migrations.CreateModel(
            name='StudentHouseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_memberships', to='school.academicyear')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='school.house')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_memberships', to='school.student')),
            ],
            options={
                'verbose_name': 'student house membership',
                'verbose_name_plural': 'student house memberships',
                'ordering': ['-academic_year', 'house', 'student'],
                'indexes': [models.Index(fields=['academic_year', 'house'], name='school_stud_academi_5ca217_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_house_per_year')],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='school.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='school.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='school.teacherprofile')),
            ],
            options={
                'ordering': ['-academic_year', 'class_section', 'subject'],
                'indexes': [models.Index(fields=['academic_year', 'class_section'], name='school_teac_academi_9b55dd_idx'), models.Index(fields=['academic_year', 'teacher'], name='school_teac_academi_123a85_idx'), models.Index(fields=['subject'], name='school_teac_subject_3b04e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'class_section', 'academic_year'), name='unique_teaching_assignment')],
            },
        ),
    ]
