# Generated by Django 6.1 on 2026-08-28 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_house_classteacherassignment_housemasterassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('default_audience_kind', models.CharField(blank=True, choices=[('class', 'Class section'), ('house', 'House'), ('school', 'Whole school'), ('student_group', 'Named student group'), ('selected_students', 'Selected students')], help_text='Optional hint only. Sessions may use a different audience kind.', max_length=32)),
                ('requires_subject', models.BooleanField(default=False)),
                ('takes_attendance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('unique_per_day', models.BooleanField(default=False, help_text='If set, only one staff member may hold this duty on a given date (e.g. MOD).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('audience_kind', models.CharField(choices=[('class', 'Class section'), ('house', 'House'), ('school', 'Whole school'), ('student_group', 'Named student group'), ('selected_students', 'Selected students')], max_length=32)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_sessions', to='school.academicyear')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_sessions', to='school.classsection')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_sessions', to='school.house')),
                ('responsible_staff', models.ForeignKey(limit_choices_to={'category': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_activity_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_sessions', to='school.subject')),
                ('teaching_assignment', models.ForeignKey(blank=True, help_text='Optional hint only. Historical staff is responsible_staff.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_sessions', to='school.teachingassignment')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='school.activitytype')),
            ],
            options={
                'ordering': ['-date', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], max_length=16)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='school.activitysession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='school.student')),
                ('taken_by', models.ForeignKey(limit_choices_to={'category': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries_taken', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'category': 'staff'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_session', 'student'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], max_length=16)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], max_length=16)),
                ('changed_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('changed_by', models.ForeignKey(limit_choices_to={'category': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_revisions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='school.attendanceentry')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='school.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: "Period 1" or "Remedial"', max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_slots', to='school.activitytype')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='school.routine')),
            ],
            options={
                'ordering': ['routine', 'sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='school.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='school.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='school.teacherprofile')),
                ('routine_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='school.routineslot')),
            ],
            options={
                'ordering': ['academic_year', 'class_section', 'routine_slot'],
            },
        ),
        migrations.AddField(
            model_name='activitysession',
            name='routine_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='school.routineslot'),
        ),
        migrations.CreateModel(
            name='SchoolCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_days', to='school.academicyear')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_days', to='school.routine')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffDutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_assignments', to='school.academicyear')),
                ('duty_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='school.dutytype')),
                ('staff', models.ForeignKey(limit_choices_to={'category': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='duty_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'duty_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='school.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activitysession',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_sessions', to='school.studentgroup'),
        ),
        migrations.CreateModel(
            name='StudentGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='school.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='school.student')),
            ],
            options={
                'ordering': ['group', 'student'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='school.activitysession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_participations', to='school.student')),
            ],
            options={
                'ordering': ['session', 'student'],
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_participant_per_session')],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['student', 'activity_session'], name='school_atte_student_fe1400_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['status'], name='school_atte_status_c97c53_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceentry',
            constraint=models.UniqueConstraint(fields=('activity_session', 'student'), name='unique_attendance_per_student_session'),
        ),
        migrations.AddIndex(
            model_name='attendancerevision',
            index=models.Index(fields=['entry', 'changed_at'], name='school_atte_entry_i_8ba249_idx'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_routine_name_per_year'),
        ),
        migrations.AddIndex(
            model_name='routineslot',
            index=models.Index(fields=['routine', 'start_time'], name='school_rout_routine_3cf07c_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineslot',
            constraint=models.UniqueConstraint(fields=('routine', 'sort_order'), name='unique_slot_order_per_routine'),
        ),
        migrations.AddConstraint(
            model_name='routineslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='routine_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='classtimetableentry',
            index=models.Index(fields=['academic_year', 'class_section'], name='school_clas_academi_6dd72b_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimetableentry',
            index=models.Index(fields=['teacher'], name='school_clas_teacher_3b099a_idx'),
        ),
        migrations.AddConstraint(
            model_name='classtimetableentry',
            constraint=models.UniqueConstraint(fields=('class_section', 'routine_slot'), name='unique_timetable_entry_per_class_slot'),
        ),
        migrations.AddIndex(
            model_name='schoolcalendarday',
            index=models.Index(fields=['academic_year', 'date'], name='school_scho_academi_783b27_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdutyassignment',
            index=models.Index(fields=['date', 'duty_type'], name='school_staf_date_aae37f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdutyassignment',
            index=models.Index(fields=['academic_year', 'date'], name='school_staf_academi_9b0854_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffdutyassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'duty_type', 'date'), name='unique_staff_duty_per_date'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_student_group_per_year'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['date', 'start_time'], name='school_acti_date_ba9a25_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['academic_year', 'date'], name='school_acti_academi_c7bd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['audience_kind'], name='school_acti_audienc_34ec37_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['responsible_staff', 'date'], name='school_acti_respons_17a460_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='activity_session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.UniqueConstraint(condition=models.Q(('class_section__isnull', False), ('routine_slot__isnull', False)), fields=('date', 'routine_slot', 'class_section'), name='unique_class_session_per_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.UniqueConstraint(condition=models.Q(('house__isnull', False), ('routine_slot__isnull', False)), fields=('date', 'routine_slot', 'house'), name='unique_house_session_per_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.UniqueConstraint(condition=models.Q(('routine_slot__isnull', False), ('student_group__isnull', False)), fields=('date', 'routine_slot', 'student_group'), name='unique_group_session_per_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.UniqueConstraint(condition=models.Q(('audience_kind', 'school'), ('routine_slot__isnull', False)), fields=('date', 'routine_slot'), name='unique_school_session_per_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.UniqueConstraint(condition=models.Q(('audience_kind', 'selected_students')), fields=('date', 'routine_slot', 'name'), name='unique_selected_session_per_slot_date_name'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='unique_student_in_group'),
        ),
    ]
