# Generated by Django 6.1 on 2026-08-28 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_activitytype_dutytype_activitysession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='taken_by',
            field=models.ForeignKey(help_text='Normally a Staff user. Administration may be used only as an override.', limit_choices_to={'category__in': ['staff', 'administration']}, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Staff or Administration. Required when correcting status.', limit_choices_to={'category__in': ['staff', 'administration']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerevision',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'category__in': ['staff', 'administration']}, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_section__isnull', False), ('house__isnull', True), ('student_group__isnull', True)), models.Q(('class_section__isnull', True), ('house__isnull', False), ('student_group__isnull', True)), models.Q(('class_section__isnull', True), ('house__isnull', True), ('student_group__isnull', False)), models.Q(('class_section__isnull', True), ('house__isnull', True), ('student_group__isnull', True)), _connector='OR'), name='activity_session_at_most_one_target'),
        ),
    ]
