# Generated by Django 6.1 on 2026-08-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_attendanceentry_taken_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceentry',
            options={'ordering': ['activity_session', 'student'], 'permissions': [('correct_attendance', 'Can correct attendance')]},
        ),
    ]
