# Generated by Django 6.1 on 2026-08-28 16:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_student_class_memberships(apps, schema_editor):
    Student = apps.get_model("school", "Student")
    StudentClassMembership = apps.get_model("school", "StudentClassMembership")
    existing = set(
        StudentClassMembership.objects.values_list("student_id", "academic_year_id")
    )
    to_create = []
    for student in Student.objects.iterator():
        if not student.class_section_id or not student.academic_year_id:
            continue
        key = (student.pk, student.academic_year_id)
        if key in existing:
            continue
        to_create.append(
            StudentClassMembership(
                student_id=student.pk,
                class_section_id=student.class_section_id,
                academic_year_id=student.academic_year_id,
            )
        )
        existing.add(key)
    if to_create:
        StudentClassMembership.objects.bulk_create(to_create)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_attendanceentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_memberships', to='school.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='school.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_memberships', to='school.student')),
            ],
            options={
                'verbose_name': 'student class membership',
                'verbose_name_plural': 'student class memberships',
                'ordering': ['-academic_year', 'class_section', 'student'],
                'indexes': [models.Index(fields=['academic_year', 'class_section'], name='school_stud_academi_8223c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_class_per_year')],
            },
        ),
        migrations.RunPython(backfill_student_class_memberships, noop_reverse),
    ]
