# Generated by Django 6.1 on 2026-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_studentclassmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
