# Generated by Django 6.1 on 2026-08-28 19:05

from django.conf import settings
from django.db import migrations, models


def backfill_enforces_unique_per_day(apps, schema_editor):
    StaffDutyAssignment = apps.get_model("school", "StaffDutyAssignment")
    DutyType = apps.get_model("school", "DutyType")
    unique_ids = DutyType.objects.filter(unique_per_day=True).values_list("pk", flat=True)
    StaffDutyAssignment.objects.filter(duty_type_id__in=unique_ids).update(
        enforces_unique_per_day=True
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_routineslot_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdutyassignment',
            name='enforces_unique_per_day',
            field=models.BooleanField(default=False, editable=False, help_text='Copied from the duty type so unique-per-day duties can be constrained in the database.'),
        ),
        migrations.RunPython(backfill_enforces_unique_per_day, noop_reverse),
        migrations.AddConstraint(
            model_name='staffdutyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('enforces_unique_per_day', True)), fields=('date', 'academic_year'), name='unique_unique_per_day_duty_per_date_year'),
        ),
    ]
