# Generated by Django 6.1 on 2026-09-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_staffdutyassignment_unique_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='school.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='school.student')),
            ],
            options={
                'verbose_name': 'student guardian',
                'verbose_name_plural': 'student guardians',
                'ordering': ['parent_profile', 'student'],
                'constraints': [models.UniqueConstraint(fields=('parent_profile', 'student'), name='unique_parent_student_guardian')],
            },
        ),
    ]
