# Generated by Django 6.1 on 2026-09-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_studentguardian'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='house',
            name='unique_house_code_when_set',
        ),
        migrations.RemoveField(
            model_name='house',
            name='code',
        ),
    ]
