# Generated by Django 6.1 on 2026-09-11 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_house_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housemasterassignment',
            options={'ordering': ['-academic_year', 'house', 'role'], 'verbose_name': 'house teacher assignment', 'verbose_name_plural': 'house teacher assignments'},
        ),
        migrations.AddField(
            model_name='housemasterassignment',
            name='role',
            field=models.CharField(choices=[('house_teacher', 'House Teacher'), ('assistant_house_teacher', 'Assistant House Teacher')], default='house_teacher', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='housemasterassignment',
            constraint=models.UniqueConstraint(fields=('house', 'academic_year', 'role'), name='unique_house_staff_role_per_year'),
        ),
    ]
