# Generated by Django 6.1 on 2026-09-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_house_staff_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsection',
            options={'ordering': ['grade_name', 'section_name'], 'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterField(
            model_name='activitysession',
            name='audience_kind',
            field=models.CharField(choices=[('class', 'Class'), ('house', 'House'), ('school', 'Whole school'), ('student_group', 'Named student group'), ('selected_students', 'Selected students')], max_length=32),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='default_audience_kind',
            field=models.CharField(blank=True, choices=[('class', 'Class'), ('house', 'House'), ('school', 'Whole school'), ('student_group', 'Named student group'), ('selected_students', 'Selected students')], help_text='Optional hint only. Sessions may use a different audience kind.', max_length=32),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='grade_name',
            field=models.CharField(help_text='Class/grade label stored in the database, e.g. VI or XI.', max_length=20, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='section_name',
            field=models.CharField(help_text='Section or stream stored in the database, e.g. A or Science.', max_length=30, verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.classsection', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='studentclassmembership',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='school.classsection', verbose_name='class'),
        ),
    ]
