# Generated by Django 6.1 on 2026-09-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_class_labels_and_audience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsection',
            options={'ordering': ['grade_number', 'section_name', 'display_name'], 'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_section__grade_number', 'class_section__section_name', 'roll_number', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='classsection',
            name='grade_number',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Sort key so classes appear in seniority order (VI before IX).'),
        ),
        migrations.AddIndex(
            model_name='classsection',
            index=models.Index(fields=['grade_number', 'section_name'], name='school_clas_grade_n_aa2692_idx'),
        ),
    ]
