# Generated by Django 6.1 on 2026-09-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_class_seniority_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGradeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20)),
                ('show_assistant_class_teacher', models.BooleanField(default=False, help_text='If enabled, this class page shows an Assistant Class Teacher.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_grade_options', to='school.academicyear')),
            ],
            options={
                'verbose_name': 'class options',
                'verbose_name_plural': 'class options',
                'ordering': ['-academic_year', 'grade_name'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'grade_name'), name='unique_class_grade_options_per_year')],
            },
        ),
        migrations.CreateModel(
            name='ClassGradeStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('class_teacher', 'Class Teacher'), ('assistant_class_teacher', 'Assistant Class Teacher')], default='class_teacher', max_length=32)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_grade_staff_assignments', to='school.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_grade_assignments', to='school.teacherprofile')),
            ],
            options={
                'verbose_name': 'class grade staff assignment',
                'verbose_name_plural': 'class grade staff assignments',
                'ordering': ['-academic_year', 'grade_name', 'role'],
                'constraints': [models.UniqueConstraint(fields=('grade_name', 'academic_year', 'role'), name='unique_class_grade_staff_role_per_year')],
            },
        ),
    ]
