# Generated by Django 6.1 on 2026-09-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_class_staff_per_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='area_type',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban')], help_text='Rural or urban, as used in JNV admission.', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, verbose_name="father's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=120, verbose_name="mother's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='native_district',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='social_category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], max_length=16, verbose_name='category'),
        ),
    ]
