# Generated by Django 6.1 on 2026-09-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_student_jnv_basic_details'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classgradestaffassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'class_section', 'academic_year'), name='unique_teacher_per_class_section_year'),
        ),
    ]
