# Generated by Django 6.1 on 2026-09-11 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_unique_teacher_per_class_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBiodataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_biodata_rows', to='school.student')),
            ],
            options={
                'verbose_name': 'student biodata row',
                'verbose_name_plural': 'student biodata rows',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'label'), name='unique_student_biodata_label')],
            },
        ),
    ]
