# Generated by Django 6.1 on 2026-09-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_extra_biodata_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_duty', 'OD'), ('sick', 'Sick'), ('leave', 'Leave')], max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancerevision',
            name='new_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_duty', 'OD'), ('sick', 'Sick'), ('leave', 'Leave')], max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancerevision',
            name='old_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_duty', 'OD'), ('sick', 'Sick'), ('leave', 'Leave')], max_length=16),
        ),
    ]
