# Generated by Django 6.1 on 2026-09-11 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_attendance_od_sick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('evening_snacks', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VidyalayaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jawahar Navodaya Vidyalaya', max_length=160)),
                ('district', models.CharField(default='Demonstration', max_length=80)),
                ('state', models.CharField(default='Madhya Pradesh', max_length=80)),
                ('nvs_region', models.CharField(default='Bhopal', max_length=80)),
                ('udise_code', models.CharField(blank=True, max_length=20)),
                ('established_year', models.PositiveSmallIntegerField(default=1986)),
                ('motto', models.CharField(default='Pragyanam Brahma', max_length=80)),
                ('about', models.TextField(blank=True, default='A residential co-educational school under Navodaya Vidyalaya Samiti, Ministry of Education, Government of India. Classes VI–XII, house system, and a common daily routine of PT, assembly, studies, games, and night roll call.')),
            ],
            options={
                'verbose_name': 'vidyalaya profile',
                'verbose_name_plural': 'vidyalaya profile',
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Whole vidyalaya'), ('staff', 'Staff and administration'), ('parents', 'Parents')], default='all', max_length=16)),
                ('published_on', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circulars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_on', '-pk'],
                'indexes': [models.Index(fields=['is_published', 'audience', 'published_on'], name='school_circ_is_publ_fd26ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('expected_return', models.TimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=120)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('escort_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('out', 'Out of campus'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='approved', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.ForeignKey(limit_choices_to={'category__in': ('staff', 'administration')}, on_delete=django.db.models.deletion.PROTECT, related_name='outing_passes_issued', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outing_passes', to='school.student')),
            ],
            options={
                'ordering': ['-date', '-departure_time'],
                'indexes': [models.Index(fields=['date', 'status'], name='school_outi_date_124959_idx'), models.Index(fields=['student', 'date'], name='school_outi_student_62a043_idx')],
            },
        ),
    ]
