# Generated by Django 6.1 on 2026-09-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_east_singhbhum_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['accession_no'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vmc', 'Vidyalaya Management Committee'), ('vac', 'Vidyalaya Advisory Committee'), ('pac', 'Parent committee')], default='vmc', max_length=8)),
                ('role', models.CharField(max_length=120)),
                ('member_name', models.CharField(max_length=160)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_seats', to='school.academicyear')),
            ],
            options={
                'ordering': ['kind', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='school.academicyear')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_marks', models.PositiveSmallIntegerField(default=40)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='school.examterm')),
            ],
            options={
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='HouseCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('sports', 'Sports / games'), ('cultural', 'Cultural'), ('literary', 'Literary'), ('quiz', 'Quiz'), ('cca', 'CCA')], max_length=16)),
                ('held_on', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_competitions', to='school.academicyear')),
            ],
            options={
                'ordering': ['-held_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HouseCompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.housecompetition')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='school.house')),
            ],
            options={
                'ordering': ['position', 'house'],
            },
        ),
        migrations.CreateModel(
            name='LibraryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='school.librarybook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_issues', to='school.student')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='MigrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=8)),
                ('other_jnv', models.CharField(max_length=160)),
                ('stream', models.CharField(blank=True, max_length=40)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='school.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='school.student')),
            ],
            options={
                'ordering': ['direction', 'student'],
            },
        ),
        migrations.CreateModel(
            name='SickBayVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_on', models.DateField()),
                ('visited_at', models.TimeField()),
                ('complaint', models.CharField(max_length=160)),
                ('treatment', models.CharField(blank=True, max_length=200)),
                ('referred_out', models.BooleanField(default=False)),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'category__in': ('staff', 'administration')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sick_bay_visits', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_bay_visits', to='school.student')),
            ],
            options={
                'ordering': ['-visited_on', '-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('school_captain', 'School captain'), ('school_vice_captain', 'School vice-captain'), ('house_captain', 'House captain'), ('house_vice_captain', 'House vice-captain'), ('prefect', 'Prefect'), ('mess_prefect', 'Mess prefect'), ('games_captain', 'Games captain'), ('cca_captain', 'CCA captain')], max_length=32)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_offices', to='school.academicyear')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='school.house')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='school.student')),
            ],
            options={
                'ordering': ['academic_year', 'role', 'student'],
            },
        ),
        migrations.CreateModel(
            name='VidyalayaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('held_on', models.DateField()),
                ('kind', models.CharField(choices=[('assembly', 'Assembly / national day'), ('cca', 'CCA'), ('games', 'Games / sports'), ('pace', 'Pace-setting'), ('migration', 'Migration'), ('other', 'Other')], default='cca', max_length=16)),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='school.academicyear')),
            ],
            options={
                'ordering': ['-held_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_on', models.DateField()),
                ('visitor_name', models.CharField(max_length=120)),
                ('relation', models.CharField(blank=True, max_length=80)),
                ('purpose', models.CharField(default='Sunday meeting', max_length=120)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='school.student')),
            ],
            options={
                'ordering': ['-visited_on', 'visitor_name'],
            },
        ),
        migrations.CreateModel(
            name='VvnEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1500)),
                ('is_paid', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=160)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vvn_entries', to='school.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vvn_entries', to='school.student')),
            ],
            options={
                'verbose_name': 'VVN entry',
                'verbose_name_plural': 'VVN entries',
                'ordering': ['student'],
            },
        ),
        migrations.AddConstraint(
            model_name='examterm',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_exam_term_year'),
        ),
        migrations.AddConstraint(
            model_name='assessmentmark',
            constraint=models.UniqueConstraint(fields=('term', 'student', 'subject'), name='unique_mark_term_student_subject'),
        ),
        migrations.AddConstraint(
            model_name='housecompetitionresult',
            constraint=models.UniqueConstraint(fields=('competition', 'house'), name='unique_competition_house'),
        ),
        migrations.AddConstraint(
            model_name='studentoffice',
            constraint=models.UniqueConstraint(fields=('academic_year', 'role', 'house', 'student'), name='unique_student_office'),
        ),
        migrations.AddConstraint(
            model_name='vvnentry',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_vvn_student_year'),
        ),
    ]
