# Generated by Django 6.1 on 2026-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0022_jnv_operations"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTableColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, unique=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "Text")],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "student table column",
                "verbose_name_plural": "student table columns",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
