# Generated by Django 6.1 on 2026-09-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0023_student_table_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTableLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_key", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_hidden", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "student table layout",
                "verbose_name_plural": "student table layouts",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
