# Generated by Django 6.1 on 2026-09-11 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBiodataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_biodata_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user biodata row',
                'verbose_name_plural': 'user biodata rows',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='unique_user_biodata_label')],
            },
        ),
    ]
